using AdventOfCode2023;

Console.WriteLine("Day 1");
D1.Run();
D1_2.Run();
Console.WriteLine("Day 2");
D2.Run();
D2_2.Run();
Console.WriteLine("Day 3");
D3.Run();
D3_2.Run();
Console.WriteLine("Day 4");
D4.Run();
D4_2.Run();
D4_2_Alt.Run();
Console.WriteLine("Day 5");
D5.Run();
D5_2.Run();
D5_2_Alt.Run();
Console.WriteLine("Day 6");
D6.Run();
D6_2.Run();
D6_2_Alt.Run();
Console.WriteLine("Day 7");
D7.Run();
D7_2.Run();
Console.WriteLine("Day 8");
D8.Run();
D8_2.Run();
Console.WriteLine("Day 9");
D9.Run();
D9_2.Run();
Console.WriteLine("Day 10");
D10.Run();
D10_2.Run();
Console.WriteLine("Day 11");
D11.Run();
D11_2.Run();
Console.WriteLine("Day 12");
D12.Run();
D12_2.Run();
Console.WriteLine("End");
